### PR TITLE
Fix replaceSupportEmail function

### LINKED ISSUE #3910: Improve replaceSupportEmail utility function
## Description

At `utils.ts` file we have `replaceSupportEmail` function that should start using `support_email` from `environment/` API.

### PR DESCRIPTION
**Pull request by magicznyleszek**
## Checklist

1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [x] Ensure the tests pass
4. [x] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [x] Write a title and, if necessary, a description of your work suitable for publishing in our [release notes](https://community.kobotoolbox.org/tag/release-notes)
6. [x] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes

## Description

Makes the constanse setting `SUPPORT_EMAIL` being displayed in error notifications.

## Notes

Changes here:
- Had to move some things around to avoid circular dependency errors:
  - `handleApiFail` from `js/utils` to `js/api`
  - some text related functions were moved from `js/utils` to `js/textUtils`, because `replaceSupportEmail` requires `envStore`, and importing it into `js/utils` is causing dependency errors. I created new file for general text related utility functions and moved ones that will not require refactor.
- `envStore` is not using `actions` anymore, just making direct call with `api.ts`
- `replaceSupportEmail` is using email from environment endpoint
- removed `getEnvironment` Reflux action :)

## Related issues

Fixes #3910

### CODE REVIEW

File: jsapp/js/envStore.ts [hunk 1]
```diff
@@ -122,9 +157,17 @@ class EnvStore {
...
-    actions.auth.getEnvironment.completed.listen(this.onGetEnvCompleted.bind(this));
-    actions.auth.getEnvironment();
+  async fetchData() {
+    try {
+      const response = await fetchGet<EnvironmentResponse>(ENV_ENDPOINT);
+      this.onGetEnvCompleted(response);
+    } catch (err) {
+      const errorObj = err as FailResponse;
+      handleApiFail(errorObj);
+    }
```
Comment (LMNTL) [inline jsapp/js/envStore.ts:170]: This `catch` block is kind of redundant - because `fetchGet()` (without the `notifyAboutError` option set to `false`) already calls `handleApiFail()`. So if I make the `/environment` endpoint error, I see two errors:

image

**Review by LMNTL — CHANGES_REQUESTED** [review]

File: jsapp/js/envStore.ts (hunk 1 above)
Comment (magicznyleszek) [reply jsapp/js/envStore.ts]: Right! Pushed a fix :)

**Review by LMNTL — APPROVED** [review]
