### PR TITLE
Fix UI crash for drafts

### LINKED ISSUE #4377: Bug: UI crashes when trying to open draft or archived project
> Found another issue: When I access certain projects from the new project lists the screen crashes. The same project can be opened fine from the side bar. [screen-crash-from-project-list.mov](https://chat.kobotoolbox.org/user_uploads/2/88/ahKHfRAbcHMxqotFKHPBhUsL/screen-crash-from-project-list.mov)

> From my testing it seems like it happens to any project that is draft or archived. It doesn't happen to deployed projects. See video.

### PR DESCRIPTION
**Pull request by magicznyleszek**
## Description

Fixing a bug on unreleased code.

## Related issues

Fixes #4377

### CODE REVIEW

File: jsapp/js/components/formSummaryProjectInfo.tsx [hunk 1]
```diff
@@ -44,8 +44,13 @@ export default function FormSummaryProjectInfo(
...
 
-  const lastDeployedDate =
-    props.asset.deployed_versions?.results[0].date_modified;
+  let lastDeployedDate;
+  if (
+    props.asset.deployed_versions?.results &&
+    props.asset.deployed_versions?.results.length > 0
+  ) {
+    lastDeployedDate = props.asset.deployed_versions.results[0].date_modified;
+  }
```
Comment (p2edwards) [inline jsapp/js/components/formSummaryProjectInfo.tsx:53]: Would 

```diff
    const lastDeployedDate = 
-     props.asset.deployed_versions?.results[0].date_modified;
+     props.asset.deployed_versions?.results?.[0]?.date_modified;
```

do the same thing here?
